# Syntax reference for this file:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: DevOps with Sphinx
on: [push, pull_request]

# https://gist.github.com/c-bata/ed5e7b7f8015502ee5092a3e77937c99
jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: checkout
        uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-python
      # ^-- This gives info on matrix testing.
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # Clean and don't fail
      - name: Clean _build directory
        run: rm -rf _build      
      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      # Build sphinx
      - name: Build Sphinx docs
        run: |
          make html

      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/


# ref https://github.com/marketplace/actions/sphinx-build
